// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxOtypTgesr5yPYFOBeSid9mU33gO5uyY',
    appId: '1:819709956020:web:b2bec92536d303d0e12ce1',
    messagingSenderId: '819709956020',
    projectId: 'flutterclase-6f7b6',
    authDomain: 'flutterclase-6f7b6.firebaseapp.com',
    storageBucket: 'flutterclase-6f7b6.appspot.com',
    measurementId: 'G-F49JLWFWMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxPyhpKgU6KG41OxkU6P25TB2x162d48g',
    appId: '1:819709956020:android:d5de3f5b6e8cc71ee12ce1',
    messagingSenderId: '819709956020',
    projectId: 'flutterclase-6f7b6',
    storageBucket: 'flutterclase-6f7b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbHYKQvQkhS87uQI96TtrfpdpYzVv1r_0',
    appId: '1:819709956020:ios:002dc95fb4a1d6ece12ce1',
    messagingSenderId: '819709956020',
    projectId: 'flutterclase-6f7b6',
    storageBucket: 'flutterclase-6f7b6.appspot.com',
    iosBundleId: 'com.example.mimosDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbHYKQvQkhS87uQI96TtrfpdpYzVv1r_0',
    appId: '1:819709956020:ios:002dc95fb4a1d6ece12ce1',
    messagingSenderId: '819709956020',
    projectId: 'flutterclase-6f7b6',
    storageBucket: 'flutterclase-6f7b6.appspot.com',
    iosBundleId: 'com.example.mimosDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxOtypTgesr5yPYFOBeSid9mU33gO5uyY',
    appId: '1:819709956020:web:ea8d10304f7d5db0e12ce1',
    messagingSenderId: '819709956020',
    projectId: 'flutterclase-6f7b6',
    authDomain: 'flutterclase-6f7b6.firebaseapp.com',
    storageBucket: 'flutterclase-6f7b6.appspot.com',
    measurementId: 'G-FS98EJ1NMP',
  );

}